pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git branch : 'main',
                    url : 'https://github.com/TreAt1412/DumpRepository.git'
            }
        }
        stage('Build') {
             steps {
               withDockerRegistry(credentialsId: 'docker-hub', url: 'https://index.docker.io/v1/') {
                   sh 'docker build -t treat1412/spring:v10 .'
                   sh 'docker push treat1412/spring:v10'
               }
             }
        }
    }
}